name: Build and Push lab3 Docker Image

on:
  push:
    branches: [ master ]
    paths:
      - 'lab3/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./lab3
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/classifier-service:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/classifier-service:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/classifier-service:latest
